### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by Morris-Vseslav** [Morris-Vseslav/homepage#5]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by Morris-Vseslav1** [comment]
- LinkedIn: https://cutt.ly/6jKyYZW 
- E-mail: morrisshostak1@gmail.com
- Skype: Morris-Vseslav Shostak
