### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by Morris-Vseslav** [Morris-Vseslav/homepage#6]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by Morris-Vseslav1** [comment]
**Finished extra courses:**
• Online courses – Software testing (EPAM, 2021) https://www.training.epam.ua/
• Online courses – Basics of Software testing (QATestLab, 2020) https://training.qatestlab.com/
- Certificate: QATestLab № 359633 

**Education:** 
	• Master’s Degree in Law – with honors
	Vasyl’ Stus Donetsk National University 
	2018-2019;
	• Bachelor’s Degree in Economist
	Vinnytsia Institute of Trade and Economics, Kyiv National University of Trade and Economics
	2014-2018.
