### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by Morris-Vseslav** [Morris-Vseslav/homepage#7]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by Morris-Vseslav1** [comment]
**Work Experience:**
	• August 2020 – present – Pillar / Fornova project as a Data Assurance 
  
**Responsibilities:**
-	Bug reporting in Jira, Zendesk;
-	Create and execute test cases;
-	Cooperation with the team inside the projects;
-	Performing manual testing (regression, re-test, UI).	
			
**Professional skills:** 
	• The theoretical knowledge base in software testing: 
	- Testing Types; 
	- SDLC: Agile (Scrum, Kanban);
	• Experience in Writing (Bug Reports, Test Cases, Checklist, Test Plan);  
	• Basic mastering HTML\CSS.

**Tools:** 
	• Jira; • Zendesk; • Moba; • Casandra;

**Languages:**
	• English - Pre-intermediate+; • Ukrainian – native; • Russian – fluent.

**Personal skills:** 
	• Team player; 
	• Positive approach to work;
	• Good communication skills.
